# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-30 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icp_id', models.CharField(max_length=40)),
                ('direction', models.CharField(max_length=5)),
                ('interval_read', models.CharField(max_length=40)),
                ('read_timestamp', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icp_id', models.CharField(max_length=40)),
                ('matched_amount', models.CharField(max_length=15)),
                ('read_date', models.CharField(max_length=40)),
                ('read_time', models.CharField(max_length=40)),
                ('publish_datetime', models.CharField(max_length=80)),
                ('buyer_seller', models.CharField(max_length=12)),
            ],
        ),
    ]
