# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-30 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='read_timestamp',
            field=models.DateField(max_length=80),
        ),
        migrations.AlterField(
            model_name='detail',
            name='publish_datetime',
            field=models.DateField(max_length=80),
        ),
    ]
