# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-30 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20181130_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icp_id', models.CharField(max_length=40)),
                ('matched_amount', models.CharField(max_length=15)),
                ('read_date', models.CharField(max_length=40)),
                ('read_time', models.CharField(max_length=40)),
                ('publish_datetime', models.DateTimeField(max_length=80)),
                ('buyer_seller', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='detail',
        ),
        migrations.AlterField(
            model_name='bill',
            name='read_timestamp',
            field=models.DateTimeField(max_length=80),
        ),
    ]
