# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-30 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20181130_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='icp_id',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='bill',
            name='interval_read',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bill',
            name='read_timestamp',
            field=models.DateTimeField(max_length=40),
        ),
        migrations.AlterField(
            model_name='output',
            name='icp_id',
            field=models.IntegerField(max_length=40),
        ),
        migrations.AlterField(
            model_name='output',
            name='matched_amount',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='output',
            name='publish_datetime',
            field=models.DateTimeField(max_length=40),
        ),
        migrations.AlterField(
            model_name='output',
            name='read_date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='output',
            name='read_time',
            field=models.CharField(max_length=10),
        ),
    ]
